// src/lib/prompt-generator.ts
// プロンプト自動生成ロジック

import {
    DEFAULT_SYSTEM_PROMPT,
    PAGE_TYPE_INSTRUCTIONS,
    analyzeCommentStyle,
    CommentStyle
} from './prompts';
import { estimatePageType } from './pdf-utils';

/**
 * プロンプト生成の入力
 */
export interface GeneratePromptInput {
    pageNumber: number;
    pageTitle: string;
    previousComment: string;
    pageType?: string;
}

/**
 * 生成されたプロンプト
 */
export interface GeneratedPrompt {
    pageNumber: number;
    pageTitle: string;
    prompt: string;
    style: CommentStyle;
    isAutoGenerated: boolean;
}

/**
 * ページタイプに応じた分析指示を取得
 */
function getAnalysisInstruction(pageType: string): string {
    return PAGE_TYPE_INSTRUCTIONS[pageType] || PAGE_TYPE_INSTRUCTIONS['other'];
}

/**
 * スタイル説明を生成
 */
function formatStyleDescription(style: CommentStyle): string {
    const formatDesc = {
        bullet: '箇条書き形式',
        paragraph: '文章形式',
        mixed: '混合形式（文章＋箇条書き）',
    }[style.format];

    const toneDesc = {
        formal: '丁寧語',
        casual: '一般的な敬語',
        neutral: '標準的な文体',
    }[style.tone];

    const parts = [
        formatDesc,
        `約${style.averageCharCount}文字`,
        style.hasNumbers ? '数値データを含む' : null,
        style.hasSections ? 'セクション分けあり' : null,
        toneDesc,
    ].filter(Boolean);

    return parts.join('、');
}

/**
 * 個別ページのプロンプトを自動生成
 */
export function generatePagePrompt(input: GeneratePromptInput): GeneratedPrompt {
    const { pageNumber, pageTitle, previousComment } = input;

    // ページタイプを推定
    const pageType = input.pageType || estimatePageType(pageTitle);

    // 前月コメントのスタイルを分析
    const style = analyzeCommentStyle(previousComment);

    // 分析指示を取得
    const analysisInstruction = getAnalysisInstruction(pageType);

    // スタイル説明
    const styleDescription = formatStyleDescription(style);

    // 言及項目のリスト
    const mentionedItemsText = style.mentionedItems.length > 0
        ? `言及している項目: ${style.mentionedItems.join('、')}`
        : '';

    // プロンプトを構築
    const prompt = `【${pageTitle}】

分析観点:
${analysisInstruction}

前月コメントのスタイル:
${styleDescription}
${mentionedItemsText}

前月コメント（参照用 - このトーン・スタイルを踏襲してください）:
「${previousComment}」

上記を参考に、今月のデータに基づいたコメントを生成してください。`;

    return {
        pageNumber,
        pageTitle,
        prompt,
        style,
        isAutoGenerated: true,
    };
}

/**
 * 複数ページのプロンプトを一括生成
 */
export function generateAllPagePrompts(
    pages: Array<{
        pageNumber: number;
        pageTitle: string;
        previousComment?: string;
    }>
): Map<number, GeneratedPrompt> {
    const prompts = new Map<number, GeneratedPrompt>();

    for (const page of pages) {
        const prompt = generatePagePrompt({
            pageNumber: page.pageNumber,
            pageTitle: page.pageTitle,
            previousComment: page.previousComment || '',
        });
        prompts.set(page.pageNumber, prompt);
    }

    return prompts;
}

/**
 * システムプロンプトを取得（カスタムまたはデフォルト）
 */
export function getSystemPrompt(customPrompt?: string): string {
    return customPrompt?.trim() || DEFAULT_SYSTEM_PROMPT;
}

/**
 * 最終的なAPIリクエスト用プロンプトを構築
 */
export function buildFinalPrompt(params: {
    systemPrompt: string;
    pagePrompt: string;
    targetPage: {
        pageNumber: number;
        pageTitle: string;
        previousComment: string;
    };
    contextPages: Array<{
        pageNumber: number;
        pageTitle: string;
    }>;
}): string {
    const { systemPrompt, pagePrompt, targetPage, contextPages } = params;

    return `${systemPrompt}

${pagePrompt}

【生成対象ページ】
- ページ番号: ${targetPage.pageNumber}
- タイトル: ${targetPage.pageTitle}

【前月コメント（参照用 - トーン・スタイルを踏襲）】
${targetPage.previousComment}

【コンテキストページ（要因分析の参考）】
${contextPages.map(p => `- P${p.pageNumber}: ${p.pageTitle}`).join('\n')}

【タスク】
上記の情報と添付画像を参照し、今月のレポートコメントを生成してください。

【添付画像の説明】
1枚目: 今月の${targetPage.pageTitle}のデータ
2枚目: 前月の${targetPage.pageTitle}（参照用）
3枚目以降: 他のページの今月データ（要因分析の参考用）`;
}
